---

- hosts: all
  become: true
  tasks:

  - name: installing and updating apache and php package
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
      update_cache: yes
