---

- hosts: all
  become: true
  tasks:

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDEUvpMFE6US0qSd5kW8J4ho1h80mTunWQIAmEXBwDR22sAhSk4uRpBJcZIRB/yH9JZNsK9USt6uxYWgKJ+3JhpJvF/dAhqXlEQOg7KzH68S+b4o9//2RMd3NP0Bm7wcQD+4n0/gUbaLwk7CT+Co+/CPjmuEU2D1GDJ0XiylRI6P96c08YsCPs9jKSeODAoCax9KzaOKuChZ/OZl5SWiLwjOTsxnwzYTRXJbhFs0Sevlg3FJ1UJmOQznePb0s50h9OtW5KpDF0MFRtEUFfViuwVsJMX2GfdayNHf3KIZXURe/MKxQtRiBgHS5Yqov7/1yq7ctkZjbtrfhctnNjqxSCQBvG7+RaplPZqhnuLfg+VE0vB6EkADYxi3n8n/fLUbDnpnaFQklyUmOhfSbg7UV5y4RB5851m0RnspKwuH6TDMQ9Ttp4UCyAk0TGTRtsPiYYSFZK/v/oC/ZlN98IqQcM6/QyNpb+7B3LVPXHTe1ksuA4AW0MEmmnnAvwy4XHFsMjCHyBHTkmeVOG/05TQ31ROuzDU23xPttT+XS9HwWWYe6UtnnlmDVs1O+S8VX5kc2x+yEq2l7P9Y3giFY7/YOCInjyDTvIsBQQp4390SUDwrDGPKmPc7MFlydsgCRpX1jePJg88pNaZFQxMevG7n2DYWB8FDcQg0WbTxx6yztN34Q== aksihlvthumar@gmail.com"
 

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: installing and updating apache and php package
    tags: apache,apache2,ubuntu
    apt:
      name: 
         - apache2
         - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: restart the server
    tags: apache, apache2, ubuntu, restart
    service:
      name: apache2
      state: restarted
    

  - name: copy default html files for site
    tags: apache, apache2, html
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (Ubuntu)
    tags: db, mariadb, ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
